### ISSUE TITLE
v3.0 crashes Matlab and other bugs

### ISSUE THREAD

**Issue by kb-** [kyamagu/mexopencv#162] opened 2015-05-30 18:18 UTC
Hi, 
I just started to use OpenCV V3 with mexopencv 3.

My fist attempt crashed Matlab 2014a and 2014b (on windows 8 x64) : 

    Img = cv.undistort(Img, A, kp);

Crash dump https://mega.co.nz/#!C0h3GTZI!-mVPIUdZ6sw5uODryuuDnBXTv3ESWOqSI_mmUI_pFks

My second attempt gave me the following error :
```
detector = cv.FeatureDetector('SURF');

Error using FeatureDetector_
Unrecognized detector SURF
Error in cv.FeatureDetector (line 80)
            this.id = FeatureDetector_(0, 'new', detectorType,
            varargin{:}); 
```

**Comment by amroamroamro** [comment] 2015-05-30 18:50
1. `cv::undistort` didn't change in OpenCV 3, so probably your crash is unrelated to the OpenCV upgrade, rather something wrong with your input to the function...

  I just tried a quick test against v3.0-rc1: `imshow(cv.undistort(rand(300), eye(3), zeros(1,4)))` and it worked fine. Can you provide a reproducible example? (please describe the size and type of the input `img`, your camera matrix `A`, and distortion coefficients).

2. SIFT and SURF (and a few others) were moved from `opencv` to `opencv_contrib`. So if you want to use those, you have to compile OpenCV from sources and enable the optional modules at compile time (`xfeatures2d` in this case). Unfortunately you can't use the precompiled OpenCV 3.x binaries downloaded from the website for the extra modules.

Finally let me say that `v3.0` mexopencv branch is still a work in progress, and considered experimental. So it is not ready for regular use just yet. The C++ source code should compile, but many M-classes and docs haven't been updated...

**Comment by kb-** [comment] 2015-05-31 23:46
1. I get the crash issue with these data (contains the image, the camera matrix and the distortion vector):
 https://mega.co.nz/#!OhZ0AZga!Lsvi8OaSaob3Zt8vbFQ1gpwOolQmJ3qmvlz39CErxdU
It happens each time I try to run this :
```
Img = rgb2gray(im2uint8(Images(:,:,:,1)));
Img = cv.undistort(Img, A1, kp1);
```

2. I compiled OpenCV. I can use xfeatures2d with Pithon but the build doesn't work with Matlab when I run ```mexopencv.make('opencv_path', 'D:\opencv3\opencv\mybuild')```

It gives e the following error :
```
Error using mexopencv.make>pkg_config (line 202)
OpenCV library path not found:
D:\opencv3\opencv\mybuild\x64\vc12\lib
Error in mexopencv.make (line 107)
    [cv_cflags,cv_libs] = pkg_config(opts); 
```

**Comment by amroamroamro** [comment] 2015-06-01 03:57
1. I tried it again on your data, but I cannot reproduce the error... The call runs fine for me and produce correct results.

2. There was a bug in `mexopencv.make` which I just fixed. Pull the latest changes in `v3.0` branch and try again :) Don't forget to specify `mexopencv.make('opencv_path','..', 'opencv_contrib',true)` to enable the extra modules.

I should note again that `v3.0` mexopencv branch is built against OpenCV 3.0-rc1 (both `opencv` and `opencv_contrib` repos). So you should checkout those exact tags when building OpenCV from sources...

**Comment by amroamroamro** [comment] 2015-06-01 04:55
The process of building OpenCV from source on Windows is a bit involved; Here is a step-by-step guide I wrote which you could follow:

1. Obtain OpenCV version 3.0-rc1. One option is to use these source tarballs (direct download links):
  - https://github.com/Itseez/opencv/archive/3.0.0-rc1.zip
  - https://github.com/Itseez/opencv_contrib/archive/3.0.0-rc1.zip

2. Extract them to some location. For example, set it so that you end up with these files in the following paths:
  - `C:\OpenCV_3.0.0_rc1\opencv\README.md`
  - `C:\OpenCV_3.0.0_rc1\opencv_contrib\README.md`

3. Start CMake-gui, and do the following:
  1. set source folder as `C:/OpenCV_3.0.0_rc1/opencv`
  2. set destination folder as: `C:/OpenCV_3.0.0_rc1/build`
  3. press configure, and choose `Visual Studio 12 2013 Win64`
  4. under "BUILD" group, deselect the following: `BUILD_DOCS`, `BUILD_PACKAGE`, `BUILD_PERF_TESTS`, `BUILD_TESTS`. Also deselect these: `BUILD_opencv_apps`, `BUILD_opencv_cuda*`, `BUILD_opencv_python2`, `BUILD_opencv_ts`.
  5. under "CPACK" group, deselect all
  6. under "OPENCV" group, set `OPENCV_EXTRA_MODULES_PATH` to `C:/OpenCV_3.0.0_rc1/opencv_contrib/modules`
  7. under "WITH" group, deselect: `WITH_CUDA`, `WITH_CUFFT`, `WITH_EIGEN`, `WITH_OPENCL*`, `WITH_VTK`
  8. press configure again
  9. under the newly added "BUILD" group (displayed in red), deselect everything except the following modules: `bgsegm`, `latentsvm`, `optflow`, `xfeatures2d`
  10. press configure yet another time
  11. press generate
  12. close CMake

4. Now we compile OpenCV. Open the solution file in Visual Studio: `C:\OpenCV_3.0.0_rc1\build\OpenCV.sln`
  1. switch configuration to "Release" mode (or "Debug" if you like)
  2. build solution (this will take a few minutes)
  3. select the "INSTALL" project in the solution explorer, and build it
  4. close Visual Studio

5. The resulting folder is: `C:\OpenCV_3.0.0_rc1\build\install` (size about 100MB in my case).
Now we add the `bin` folder (containing the OpenCV DLLs) to the PATH environment variable. In this case the directory you should add is:
  - `C:\OpenCV_3.0.0_rc1\build\install\x64\vc12\bin`

6. Download mexopencv project, and switch to the `v3.0` branch. Say you saved it to have this path:
  - `C:\mexopencv\README.markdown`

7. Start MATLAB, and run:
  ``` matlab
>> cd('C:\mexopencv')
>> addpath('C:\mexopencv')
>> addpath('C:\mexopencv\opencv_contrib')
>> mexopencv.make('opencv_path','C:\OpenCV_3.0.0_rc1\build\install', 'opencv_contrib',true)
```
  (It will take several minutes to finish compilation)

8. verify:
  ```matlab
>> cv.getBuildInformation()
```

**Comment by kb-** [comment] 2015-06-02 22:22
Thanks a lot for this great guide! I wouldn't have been able to figure out these steps all by myself. It's working now!

``` cv.undistort ``` is working
SURF is working, with the old syntax ``` cv.FeatureDetector('SURF') ``` ... That's fine for me.


I had some issues during the process but I found workarounds to make it work. Maybe it can help others : 
3.
    iv. These items weren't displayed on my side :
		``` BUILD_opencv_python2 ```
		``` CPACK ```

viii. Error :
        ``` CMake Warning at D:/OpenCV_3.0.0_rc1/opencv_contrib/modules/matlab/CMakeLists.txt:55 (message):
          A required dependency of the matlab module (PythonLibs) was not found.
          Disabling Matlab bindings... ```
        --> I had to set ``` PYTHON2 ``` and ``` PYTHON3 ``` paths (installed in 64bit with six, numpy and matplotlib)
          
2nd error :
         ``` Traceback (most recent call last):
          File "D:/OpenCV_3.0.0_rc1/opencv_contrib/modules/matlab/generator/gen_matlab.py", line 204, in <module>
            mwg.gen(args.moduleroot, args.modules, args.extra, args.outdir)
          File "D:/OpenCV_3.0.0_rc1/opencv_contrib/modules/matlab/generator/gen_matlab.py", line 32, in gen
            import rst_parser
        ImportError: No module named rst_parser ```
          
--> Missing Python module:
        I downloaded
        http://code.opencv.org/svn/gsoc2012/denoising/trunk/opencv-2.4.2/modules/java/generator/rst_parser.py
        and put it in
        D:\OpenCV_3.0.0_rc1\opencv\modules\python\src2


ix. The modules appear in the existing "BUILD" (not in red). The modules are already checked along with the ones from iv.

xi and xii. All fine except this "Warning: Matlab bindings will only be built in Release configurations" --> I guess it has to be compiled in "Release" mode to work properly


4.
Build solution gives these warnings and error:
``` Warning    1    warning C4005: 'HAVE_ROUND' : macro redefinition    c:\python27\include\pyconfig.h    444    1    opencv_python2
Warning    2    warning C4005: 'HAVE_ROUND' : macro redefinition    c:\python34\include\pyconfig.h    441    1    opencv_python3
Error    3    error LNK1104: cannot open file 'D:\OpenCV_3.0.0_rc1\build\lib\Release\cv2.pyd'    D:\OpenCV_3.0.0_rc1\build\modules\python2\LINK    opencv_python2 ```

The file is there tho...

Build INSTALL: ok

**Comment by amroamroamro** [comment] 2015-06-02 23:41
I already had Python 2.7 installed on my machine from before (along with packages like Sphinx), so I don't know if that actually matters to the process... You just wanna make sure to disable building the python module (`cv2.pyd`) or generating unnecessary rST docs.

Also you want to disable building the `matlab` contrib module (which pulls Python as prerequisite). You won't need it anyway if you're going to use `mexopencv`, both serve the same purpose!

As for the class-form of SURF (and other 2D features), the MEX-function is already compiled, we just haven't added a MATLAB class for it yet, I'll get it done soon :) The focus has been mainly on the C++ side.

**Comment by amroamroamro** [comment] 2015-07-07 22:39
@kb- 
We created updated instructions for the final OpenCV 3.0.0 version at: https://github.com/kyamagu/mexopencv/wiki

Kindly consider closing the issue if it was solved. Thanks.

**Closed** 2016-10-24 11:49 UTC
