### ISSUE TITLE
Unexpected Standard exception from MEX file.

### ISSUE THREAD

**Issue by sarmadm** [kyamagu/mexopencv#324] opened 2017-02-28 20:16 UTC
Hi

I'm using this code with mexopencv , when I run it I get this error 

```matlab
addpath('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\ZFace_src');
addpath(genpath('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\3rd_party\'));
zf = CZFace('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\ZFace_models  \zf_ctrl49_mesh512.dat','haarcascade_frontalface_alt2.xml');

h = [];
inFiles = dir('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\test_images\*.jpg');

for i = 1:length(inFiles)
    I = imread(['C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\test_images\'       inFiles(i).name]);

    [ ctrl2D, ~, ~ ] = zf.Fit( I, [] );
    [ ctrl2D, mesh2D, ~, pars ] = zf.Fit( I, ctrl2D );

    h = InitDisplay( zf, I );
    UpdateDisplay( h, zf, I, ctrl2D, mesh2D, pars );

    pause;
    close(h.fig);
end

clear zf;
```
```
Unexpected Standard exception from MEX file.
What() is:
C:\dev_opencv\opencv\modules\objdetect\src\cascadedetect.cpp:1639:
error: (-215) !empty() in function cv::CascadeClassifier::detectMultiScale

Error in cv.CascadeClassifier/detect (line 292)
            [boxes, varargout{1:nargout-1}] = CascadeClassifier_(this.id, ...
Error in CZFace/Fit
Error in Demo_Images (line 19)
    [ ctrl2D, ~, ~ ] = zf.Fit( I, [] );
```

**Comment by amroamroamro** [comment] 2017-03-01 09:44
I don't know what `CZFace` is, but the [error](https://github.com/opencv/opencv/blob/3.1.0/modules/objdetect/src/cascadedetect.cpp#L1639) from `CascadeClassifier::detectMultiScale` indicates that no model was loaded (XML file). Check that the path you provide is correct...

Usually this is how the class is used:

``` matlab
xmlfile = fullfile('C:\path\to\haarcascade_frontalface_alt2.xml');
cc = cv.CascadeClassifier(xmlfile);
boxes = cc.detect(img);
```

**Comment by amroamroamro** [comment] 2017-03-17 15:17
closing as duplicate of #328

**Closed by amroamroamro** 2017-03-17 15:17 UTC
Labels: opencv-2, question
